### ISSUE TITLE
Example, working `.env` file.

### ISSUE THREAD

**Issue by danhammer** [resource-watch/prep-app#22]
Can someone provide info on how to get the local site running?  I don't know how to appropriately set some of the arguments: 

```
API_URL=http://api.mydomain.com
RW_API_URL=http://api.mydomain.com
ASSETS_URL=http://assets.mydomain.com
```

Any hints would be greatly appreciated.  @d4weed?

**Comment by apercas** [comment]
Hi, @danhammer we're looking at right. We'll get back ASAP.

**Comment by fgassert** [comment]
Hi @danhammer,
Sorry no one got back to you on this. I think what you need are:

```
API_URL=http://api.prepdata.org
RW_API_URL=http://api.resourcewatch.org
ASSETS_URL=http://manager.prepdata.org
```

Is this correct @apercas?

**Comment by davidsingal** [comment]
hi @danhammer @fgassert 
The correct one is:
```
API_URL=http://manager.prepdata.org
RW_API_URL=http://api.resourcewatch.org
ASSETS_URL=http://manager.prepdata.org
```
